# Generated by Django 5.2 on 2025-04-11 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='administration.section'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('grade', 'section', 'subject')},
        ),
    ]
