# Generated by Django 5.2 on 2025-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_student_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
